language: node_js
node_js: node
sudo: required
services:
  - docker

script:
  - docker build -t app/event-api .

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'candidates'
  env: 'Candidates-env'
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket-name: 'elasticbeanstalk-us-east-2-978309339766'
  path: 'candidates'
  on:
    branch: main
  skip_cleanup: true
