language: node_js
node_js: node
sudo: required
services:
  - docker

script:
  - docker build -t app/recruitment .

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'recruitment-api'
  env: 'Recruitmentapi-env'
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket-name: 'elasticbeanstalk-eu-north-1-978309339766'
  path: 'recruitment-api'
  on:
    branch: main
  skip_cleanup: true
